/**
 * SVG parity tests — Python vs TypeScript SVG output.
 *
 * These tests verify that the TypeScript SVG renderer produces structurally
 * equivalent SVG output to the Python reference implementation for every preset.
 *
 * Structural comparison includes:
 * - viewBox dimensions (within tolerance)
 * - Element counts (path, text, group)
 * - Text content (all labels/dimensions present)
 * - Path data (numeric values within tolerance)
 *
 * The fixtures in tests/fixtures/python_svg_parity.json are generated by:
 *   python scripts/generate_svg_fixtures.py
 *
 * Re-run that script whenever the Python SVG rendering changes.
 */

import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { describe, test, expect } from 'vitest'
import { generateViolin } from '../instrument_generator'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SvgViewFixture {
  svg: string
  viewBox: string
  path_count: number
  text_count: number
  group_count: number
  text_contents: string[]
  path_data: string[]
}

interface SvgFixtureEntry {
  preset: string
  params: Record<string, unknown>
  views: Record<string, SvgViewFixture>
}

// ---------------------------------------------------------------------------
// Load fixtures
// ---------------------------------------------------------------------------

const fixtures: SvgFixtureEntry[] = JSON.parse(
  readFileSync(
    resolve(__dirname, '../../tests/fixtures/python_svg_parity.json'),
    'utf-8'
  )
)

// ---------------------------------------------------------------------------
// SVG parsing helpers
// ---------------------------------------------------------------------------

/** Extract the viewBox attribute from an SVG string. */
function extractViewBox(svg: string): string {
  const m = svg.match(/viewBox="([^"]*)"/)
  return m ? m[1]! : ''
}

/** Parse viewBox into 4 numbers. */
function parseViewBox(vb: string): number[] {
  return vb
    .trim()
    .split(/\s+/)
    .map(Number)
}

/** Count occurrences of a tag in an SVG string (regex-based). */
function countTag(svg: string, tag: string): number {
  // Match opening tags like <path, <text, <g
  // Avoid matching <textPath, <tspan etc for <t
  const re = new RegExp(`<${tag}[\\s/>]`, 'g')
  const matches = svg.match(re)
  return matches ? matches.length : 0
}

/** Extract all text content from <text> elements. */
function extractTextContents(svg: string): string[] {
  const results: string[] = []
  // Match <text ...>content</text> including multi-line
  const textRe = /<text[^>]*>([\s\S]*?)<\/text>/g
  let m: RegExpExecArray | null
  while ((m = textRe.exec(svg)) !== null) {
    // Strip any inner tags (like <tspan>)
    let content = m[1]!.replace(/<[^>]*>/g, '').trim()
    if (content) {
      results.push(content)
    }
  }
  return results
}

/** Extract all d="..." attribute values from <path> elements. */
function extractPathData(svg: string): string[] {
  const results: string[] = []
  const pathRe = /<path[^>]*\sd="([^"]*)"[^>]*>/g
  let m: RegExpExecArray | null
  while ((m = pathRe.exec(svg)) !== null) {
    if (m[1]) {
      results.push(m[1])
    }
  }
  return results
}

/** Extract all numeric values from a path d-attribute string. */
function extractPathNumbers(d: string): number[] {
  const nums: number[] = []
  // Match numbers (including negative and decimal)
  const re = /-?\d+\.?\d*(?:e[+-]?\d+)?/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(d)) !== null) {
    nums.push(parseFloat(m[0]))
  }
  return nums
}

/** Extract path commands (letters) from a path d-attribute string. */
function extractPathCommands(d: string): string {
  return d.replace(/[^A-Za-z]/g, '')
}

/**
 * Normalize a path d-attribute for sorting.
 *
 * Replaces every number with a fixed-precision representation so that
 * string sorting produces the same order regardless of whether the
 * source wrote "355" or "355.0".
 */
function normalizePathForSort(d: string): string {
  return d.replace(/-?\d+\.?\d*(?:e[+-]?\d+)?/gi, (m) =>
    parseFloat(m).toFixed(6)
  )
}

/**
 * Pair up Python and TypeScript paths for comparison.
 *
 * Sorts both arrays using normalized numeric representations so that
 * formatting differences (e.g. "355" vs "355.0") don't affect ordering.
 */
function pairPaths(pyPaths: string[], tsPaths: string[]): [string[], string[]] {
  const pyWithKey = pyPaths.map((p) => ({ orig: p, key: normalizePathForSort(p) }))
  const tsWithKey = tsPaths.map((p) => ({ orig: p, key: normalizePathForSort(p) }))
  pyWithKey.sort((a, b) => a.key.localeCompare(b.key))
  tsWithKey.sort((a, b) => a.key.localeCompare(b.key))
  return [pyWithKey.map((x) => x.orig), tsWithKey.map((x) => x.orig)]
}

// ---------------------------------------------------------------------------
// Fixture validation
// ---------------------------------------------------------------------------

describe('SVG parity fixtures', () => {
  test('fixture file contains presets', () => {
    expect(fixtures.length).toBeGreaterThan(0)
  })

  test('each fixture has side and cross_section views', () => {
    for (const f of fixtures) {
      expect(f.views['side']).toBeTruthy()
      expect(f.views['cross_section']).toBeTruthy()
      expect(f.views['side']!.path_count).toBeGreaterThan(0)
      expect(f.views['cross_section']!.path_count).toBeGreaterThan(0)
    }
  })
})

// ---------------------------------------------------------------------------
// Per-preset, per-view tests
// ---------------------------------------------------------------------------

const VIEW_NAMES = ['side', 'cross_section'] as const

for (const fixture of fixtures) {
  describe(`SVG parity — ${fixture.preset}`, () => {
    // Generate TS result once per preset
    const tsResult = generateViolin(fixture.params)

    test('TS generation succeeds', () => {
      expect(tsResult.success).toBe(true)
      expect(tsResult.views).toBeTruthy()
    })

    for (const viewName of VIEW_NAMES) {
      const pyView = fixture.views[viewName]
      if (!pyView || pyView.path_count === 0) continue

      describe(`${viewName} view`, () => {
        const tsSvg = tsResult.views?.[viewName] ?? ''

        test('produces valid SVG', () => {
          expect(tsSvg).toMatch(/^<svg/)
          expect(tsSvg).toContain('</svg>')
        })

        // ----- viewBox -----
        test('viewBox dimensions match (within 1 unit)', () => {
          const pyVB = parseViewBox(pyView.viewBox)
          const tsVB = parseViewBox(extractViewBox(tsSvg))
          expect(pyVB).toHaveLength(4)
          expect(tsVB).toHaveLength(4)
          for (let i = 0; i < 4; i++) {
            expect(tsVB[i]).toBeCloseTo(pyVB[i]!, 0)
          }
        })

        // ----- Element counts -----
        test('path count matches', () => {
          const tsPathCount = countTag(tsSvg, 'path')
          expect(tsPathCount).toBe(pyView.path_count)
        })

        test('text count matches', () => {
          const tsTextCount = countTag(tsSvg, 'text')
          expect(tsTextCount).toBe(pyView.text_count)
        })

        test('group count matches', () => {
          const tsGroupCount = countTag(tsSvg, 'g')
          expect(tsGroupCount).toBe(pyView.group_count)
        })

        // ----- Text content -----
        test('all Python text labels appear in TS output', () => {
          const tsTexts = extractTextContents(tsSvg)
          for (const pyText of pyView.text_contents) {
            // For numeric dimension labels, allow small formatting differences
            // (e.g. "3.50" vs "3.5"). Compare the numeric value if it looks like a number.
            const pyNum = parseFloat(pyText)
            if (!isNaN(pyNum) && /^-?\d+\.?\d*$/.test(pyText.trim())) {
              // It's a pure number — check that some TS text parses to the same value
              const found = tsTexts.some((t) => {
                const tsNum = parseFloat(t)
                return !isNaN(tsNum) && Math.abs(tsNum - pyNum) < 0.15
              })
              expect(found).toBe(true)
            } else {
              // Text label — check for exact presence
              const found = tsTexts.some((t) => t === pyText)
              expect(found).toBe(true)
            }
          }
        })

        // ----- Path data -----
        test('path data numeric values match (within 0.01)', () => {
          const pyPaths = pyView.path_data
          const tsPaths = extractPathData(tsSvg)

          // Compare sorted by normalized numeric representation
          // so that formatting differences (e.g. "355" vs "355.0")
          // don't cause misaligned pairing.
          expect(tsPaths.length).toBe(pyPaths.length)

          const [pySorted, tsSorted] = pairPaths(pyPaths, tsPaths)

          for (let i = 0; i < pySorted.length; i++) {
            const pyNums = extractPathNumbers(pySorted[i]!)
            const tsNums = extractPathNumbers(tsSorted[i]!)

            // Same number of numeric values
            expect(tsNums.length).toBe(pyNums.length)

            // Each numeric value matches within tolerance
            for (let j = 0; j < pyNums.length; j++) {
              expect(tsNums[j]).toBeCloseTo(pyNums[j]!, 2)
            }
          }
        })

        test('path commands match exactly', () => {
          const pyPaths = pyView.path_data
          const tsPaths = extractPathData(tsSvg)

          const [pySorted, tsSorted] = pairPaths(pyPaths, tsPaths)
          const pyCmds = pySorted.map(extractPathCommands)
          const tsCmds = tsSorted.map(extractPathCommands)

          expect(tsCmds).toEqual(pyCmds)
        })
      })
    }
  })
}
