/**
 * Python / TypeScript parity tests.
 *
 * These tests verify that the TypeScript geometry engine produces identical
 * numerical results to the Python reference implementation for every preset.
 *
 * The fixtures in tests/fixtures/python_parity.json are generated by:
 *   python scripts/generate_ts_fixtures.py
 *
 * Re-run that script whenever the Python geometry engine changes.
 *
 * Ported from web/ts-parity.test.js to Vitest format.
 */

import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { describe, test, expect } from 'vitest'

import { calculateFretPositions, calculateSagitta } from '../geometry_engine'
import { calculateDerivedValues } from '../instrument_geometry'
import { generateViolin } from '../instrument_generator'

const __dirname = dirname(fileURLToPath(import.meta.url))

interface FixtureEntry {
  preset: string
  params: Record<string, unknown>
  expected: {
    derived_values: Record<string, number | null>
    fret_positions: number[]
  }
}

const fixtures: FixtureEntry[] = JSON.parse(
  readFileSync(resolve(__dirname, '../../tests/fixtures/python_parity.json'), 'utf-8')
)

// ── Fixture validation ────────────────────────────────────────────────────

describe('parity fixtures', () => {
  test('fixture file contains presets', () => {
    expect(fixtures.length).toBeGreaterThan(0)
  })

  test('each fixture has params, derived_values, and fret_positions', () => {
    for (const f of fixtures) {
      expect(f.preset).toBeTruthy()
      expect(f.params).toBeTruthy()
      expect(Object.keys(f.expected.derived_values).length).toBeGreaterThan(10)
      expect(Array.isArray(f.expected.fret_positions)).toBe(true)
    }
  })

  test('covers all three instrument families', () => {
    const families = new Set(fixtures.map(f => f.params['instrument_family']))
    expect(families).toContain('VIOLIN')
    expect(families).toContain('VIOL')
    expect(families).toContain('GUITAR_MANDOLIN')
  })

  test('neck_angle is present and non-zero for all presets', () => {
    for (const f of fixtures) {
      const angle = f.expected.derived_values['neck_angle']
      expect(typeof angle).toBe('number')
      expect(Math.abs(angle!)).toBeGreaterThan(0)
    }
  })
})


// ── Step 1: fret positions ───────────────────────────────────────────────

describe.each(fixtures)('fret positions — $preset', ({ preset: _preset, params, expected }) => {
  test('match Python to 6 decimal places', () => {
    const vsl = params['vsl'] as number
    const noFrets = params['no_frets'] as number
    const positions = calculateFretPositions(vsl, noFrets)
    expect(positions.length).toBe(expected.fret_positions.length)
    positions.forEach((pos, i) => {
      expect(pos).toBeCloseTo(expected.fret_positions[i]!, 6)
    })
  })
})

// Sagitta spot check (not in the original parity test but validates calculateSagitta)
describe('core geometry — calculateSagitta', () => {
  test('sagitta is non-negative', () => {
    const sagitta = calculateSagitta(300, 40)
    expect(sagitta).toBeGreaterThanOrEqual(0)
  })
})


// ── Step 2: derived values ───────────────────────────────────────────────

describe.each(fixtures)('derived values — $preset', ({ preset: _preset, params, expected }) => {
  test('match Python to 4 decimal places', () => {
    const result = calculateDerivedValues(params as Record<string, unknown>)
    for (const [key, pythonValue] of Object.entries(expected.derived_values)) {
      if (pythonValue === null) continue
      expect(result[key]).toBeCloseTo(pythonValue, 4)
    }
  })
})


// ── Step 3: full pipeline ────────────────────────────────────────────────

describe.each(fixtures)('full pipeline — $preset', ({ preset: _preset, params, expected }) => {
  test('succeeds without errors', () => {
    const result = generateViolin(params as Record<string, unknown>)
    expect(result.success).toBe(true)
    expect(result.errors).toHaveLength(0)
  })

  test('derived values match Python to 4 decimal places', () => {
    const result = generateViolin(params as Record<string, unknown>)
    for (const [key, pythonValue] of Object.entries(expected.derived_values)) {
      if (pythonValue === null) continue
      expect(result.derived_values![key]).toBeCloseTo(pythonValue, 4)
    }
  })

  test('produces side view SVG', () => {
    const result = generateViolin(params as Record<string, unknown>)
    expect(result.views!['side']).toMatch(/^<svg/)
    expect(result.views!['side']).toContain('</svg>')
  })
})
