/**
 * Python / TypeScript parity tests.
 *
 * These tests verify that the TypeScript geometry engine produces identical
 * numerical results to the Python reference implementation for every preset.
 *
 * The fixtures in tests/fixtures/python_parity.json are generated by:
 *   python scripts/generate_ts_fixtures.py
 *
 * Re-run that script whenever the Python geometry engine changes.
 *
 * --- HOW TO ACTIVATE THESE TESTS ---
 *
 * As each TypeScript module is completed, uncomment the relevant section below.
 * The fixture-validation tests at the top run immediately and serve as a
 * sanity check that the fixture file itself is complete and well-formed.
 *
 * Porting order:
 *   1. geometry_engine.ts   → uncomment 'fret positions' and 'core geometry' tests
 *   2. instrument_geometry.ts → uncomment 'derived values' test
 *   3. instrument_generator.ts → uncomment 'full pipeline' test
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const fixtures = JSON.parse(
  readFileSync(resolve(__dirname, '../tests/fixtures/python_parity.json'), 'utf-8')
);

// ─── Step 1: uncomment as geometry_engine.ts is completed ────────────────────
// import { calculateFretPositions, calculateSagitta } from '../src-ts/geometry_engine.js'

// ─── Step 2: uncomment as instrument_geometry.ts is completed ────────────────
// import { calculateDerivedValues } from '../src-ts/instrument_geometry.js'

// ─── Step 3: uncomment as instrument_generator.ts is completed ───────────────
// import { generateViolin } from '../src-ts/instrument_generator.js'
// ─────────────────────────────────────────────────────────────────────────────


// ── Fixture validation (runs now) ────────────────────────────────────────────

describe('parity fixtures', () => {
  test('fixture file contains presets', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  test('each fixture has params, derived_values, and fret_positions', () => {
    for (const f of fixtures) {
      expect(f.preset).toBeTruthy();
      expect(f.params).toBeTruthy();
      expect(Object.keys(f.expected.derived_values).length).toBeGreaterThan(10);
      expect(Array.isArray(f.expected.fret_positions)).toBe(true);
    }
  });

  test('covers all three instrument families', () => {
    const families = new Set(fixtures.map(f => f.params.instrument_family));
    expect(families).toContain('VIOLIN');
    expect(families).toContain('VIOL');
    expect(families).toContain('GUITAR_MANDOLIN');
  });

  test('neck_angle is present and non-zero for all presets', () => {
    for (const f of fixtures) {
      const angle = f.expected.derived_values.neck_angle;
      expect(typeof angle).toBe('number');
      expect(Math.abs(angle)).toBeGreaterThan(0);
    }
  });
});


// ── Step 1: fret positions (activate when geometry_engine.ts is ready) ───────

/*
describe.each(fixtures)('fret positions — $preset', ({ preset, params, expected }) => {
  test('match Python to 6 decimal places', () => {
    const positions = calculateFretPositions(params.vsl, params.no_frets);
    expect(positions.length).toBe(expected.fret_positions.length);
    positions.forEach((pos, i) => {
      expect(pos).toBeCloseTo(expected.fret_positions[i], 6);
    });
  });
});
*/


// ── Step 2: derived values (activate when instrument_geometry.ts is ready) ───

/*
describe.each(fixtures)('derived values — $preset', ({ preset, params, expected }) => {
  test('match Python to 4 decimal places', () => {
    const result = calculateDerivedValues(params);
    for (const [key, pythonValue] of Object.entries(expected.derived_values)) {
      if (pythonValue === null) continue;
      expect(result[key]).toBeCloseTo(pythonValue, 4);
    }
  });
});
*/


// ── Step 3: full pipeline (activate when instrument_generator.ts is ready) ───

/*
describe.each(fixtures)('full pipeline — $preset', ({ preset, params, expected }) => {
  test('succeeds without errors', () => {
    const result = generateViolin(params);
    expect(result.success).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  test('derived values match Python to 4 decimal places', () => {
    const result = generateViolin(params);
    for (const [key, pythonValue] of Object.entries(expected.derived_values)) {
      if (pythonValue === null) continue;
      expect(result.derived_values[key]).toBeCloseTo(pythonValue, 4);
    }
  });

  test('produces side view SVG', () => {
    const result = generateViolin(params);
    expect(result.views.side).toMatch(/^<svg/);
    expect(result.views.side).toContain('</svg>');
  });
});
*/
